language: node_js
node_js:
  - "10"

cache: yarn

branches:
  only:
    - master

install:
  - yarn
  - yarn workspace web export-gh-pages

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  local-dir: packages/web/build
  on:
    branch: master
